# Generated by Django 2.0 on 2018-08-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.Book'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='checkout_time',
            field=models.DateTimeField(null=True),
        ),
    ]
