# Generated by Django 2.0 on 2018-08-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_auto_20180817_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
