# Generated by Django 2.0 on 2018-08-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_auto_20180817_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrower',
            old_name='book',
            new_name='books',
        ),
    ]
