# Generated by Django 2.0 on 2018-08-20 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0014_auto_20180817_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='book',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Borrower',
        ),
    ]
