# Generated by Django 2.0 on 2018-08-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0015_auto_20180820_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
