# Generated by Django 2.0 on 2018-08-09 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=200, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 8, 9, 20, 55, 5, 513072))),
            ],
        ),
    ]
